class Sync_m::Err
  # --- Fail(*options) -> ()
  # 
  # 自身に定義されているメッセージをセットして例外を発生させます。
  def Fail; end

end
